### PR TITLE
added roles in schema of notifications for alert configurations

### PR DESCRIPTION
**Pull request by coderGo93**
- Added field `roles` for schema `notification`
- Added value for roles in config of tf because now it's required for test

### CODE REVIEW

**Review by marinsalinas — CHANGES_REQUESTED** [review]
Could.you add this field into the website documentation?

**Comment by coderGo93** [comment]
> Could.you add this field into the website documentation?

you're right, I forgot that, just updated documentation, thank you @marinsalinas

**Review by themantissa — CHANGES_REQUESTED** [review]
This PR shouldn't need to modify the go files (mod/sum).   Unless there's a reason they shouldn't be merged in.  otherwise lgtm.

**Comment by marinsalinas** [comment]
> This PR shouldn't need to modify the go files (mod/sum). Unless there's a reason they shouldn't be merged in. otherwise lgtm.

Actually it should because this PR needs a new version of the client but, just he should remove the `replace` line in go.mod and update to the latest version of the client.

**Comment by themantissa** [comment]
Thank you @marinsalinas  - I knew something looked a bit wrong.

**Review by marinsalinas — CHANGES_REQUESTED** [review]
Please run `go mod vendor` and commit as `chore: update vendor dependencies", avoiding this causes Travis to fail.

**Review by themantissa — APPROVED** [review]
With fixes and checks passing LGTM, @marinsalinas your turn :)

**Review by PacoDw — APPROVED** [review]
LGTM!

**Pull request merged**
