### PR TITLE
INTMDB-236: Updated the cluster configuration

### PR DESCRIPTION
**Pull request by coderGo93**
## Description

- Updated the examples, tests to follow a better configuration for cluster

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

### CODE REVIEW

**Comment by themantissa** [comment]
@coderGo93  this needs a DoU person to review as well.

**Review by themantissa — APPROVED** [review]
LGTM!

**Review by gssbzn — APPROVED** [review]
LGTM

**Review by thetonymaster — APPROVED** [review]
LGTM

**Pull request merged**
