### PR TITLE
INTMDB-784: microsoft_teams_webhook_url keeps updating on every apply

### PR DESCRIPTION
**Pull request by maastha**
## Description

Added fix to prevent microsoft_teams_webhook_url updating on every apply.

_Jira ticket:_ [INTMDB-784](https://jira.mongodb.org/browse/INTMDB-784)

Link to any related issue(s):

## Type of change:

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [X] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [X] I have read the [contribution guidelines](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/CONTRIBUTING.md)
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

### CODE REVIEW

**Comment by Zuhairahmed** [comment]
@maastha minor point, do you mind adding JIRA ticket link to PR description so little easier for Martin/others to review?

**Review by martinstibbe — APPROVED** [review]
LGTM

**Review by Zuhairahmed — CHANGES_REQUESTED** [review]
@maastha do you mind also committing this to v1.10.0 release staging branch (instead of master)? we are planning on releasing v1.9.0 this week and that sprint cycle is already complete.

**Comment by maastha** [comment]
> @maastha do you mind also committing this to v1.10.0 release staging branch (instead of master)? we are planning on releasing v1.9.0 this week and that sprint cycle is already complete.

@Zuhairahmed updated base branch

**Review by Zuhairahmed — APPROVED** [review]
LGTM

**Pull request merged**
