### PR TITLE
Update defaults in Project Settings

### PR DESCRIPTION
**Pull request by Zuhairahmed**
## Description

Please include a summary of the fix/feature/change, including any relevant motivation and context.
Updating project defaults to be inline with project creation defaults in Atlas UI + Atlas Admin API

image

Link to any related issue(s): https://mongodb.slack.com/archives/CLB2CJ1JB/p1682446602596629?thread_ts=1682434093.489889&cid=CLB2CJ1JB 

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have read the [contribution guidelines](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/CONTRIBUTING.md)
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

### CODE REVIEW

**Review by martinstibbe — COMMENTED** [review]
This may break users that do not have values set in existing config i.e. value is null and they have feature turned off

**Review by andreaangiolillo — CHANGES_REQUESTED** [review]
The resource uses this endpoint [createProject](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/#tag/Projects/operation/createProject) which does not allow you to set these values.

**Review by themantissa — CHANGES_REQUESTED** [review]
@Zuhairahmed I think engineering should figure this out, not product.  We don't want to set defaults in Terraform.   Terraform should honor the defaults of the system as it could change.  Terraform should only change from the system default if the user specifically sets another value.

**Comment by Zuhairahmed** [comment]
Thanks @martinstibbe @andreaangiolillo @themantissa closing this PR and captured as part of https://jira.mongodb.org/browse/INTMDB-789 to investigate this one further

**Pull request closed without merging**
