### PR TITLE
Fix #171: added validation to avoid nil type error

### LINKED ISSUE #171: TERRAFORM CRASH on importing mongodbatlas_alert_configuration
Terraform import worked for other `mongodbatlas_alert_configuration`, but not for this one.

```
terraform import mongodbatlas_alert_configuration.replication_oplog_window 5e384f0dcf09a208528fb22d-5e384f0dcf09a208528fb22e
mongodbatlas_alert_configuration.replication_oplog_window: Importing from ID "5e384f0dcf09a208528fb22d-5e384f0dcf09a208528fb22e"...

Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: invalid memory address or nil pointer dereference
```

[crash.log](https://github.com/terraform-providers/terraform-provider-mongodbatlas/files/4330913/crash.log)

### PR DESCRIPTION
**Pull request by PacoDw**
closes #171

### CODE REVIEW

**Review by marinsalinas — APPROVED** [review]
LGTM!

**Review by themantissa — APPROVED** [review]
LGTM, thank you for the quick fix on the crash report!

**Comment by themantissa** [comment]
@PacoDw are you waiting to merge for a reason?  If not it's good to go.

**Comment by PacoDw** [comment]
Thanks @themantissa :)

**Pull request merged**
