### PR TITLE
INTMDB-466 - Added is_extended_storage_sizes_enabled

### PR DESCRIPTION
**Pull request by evertsd**
## Description

Added is_extended_storage_sizes_enabled project setting

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have read the [contribution guidelines](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/CONTRIBUTING.md)
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

### CODE REVIEW

**Comment by Zuhairahmed** [comment]
@evertsd appears there a few failing GitHub tests, do you mind resolving first before we review?

**Comment by Zuhairahmed** [comment]
@evertsd appears there are few branch conflicts on this PR, can you resolve?

**Comment by evertsd** [comment]
Alright @Zuhairahmed I've fixed up those few issues

**Review by Zuhairahmed — APPROVED** [review]
LGTM pending APIx team, @themantissa and @martinstibbe review

**Review by andreaangiolillo — APPROVED** [review]
LGTM

**Review by themantissa — APPROVED** [review]
LGTM!

**Review by martinstibbe — APPROVED** [review]
LGTM

**Pull request merged**
