### PR TITLE
Update teams.html.markdown

### PR DESCRIPTION
**Pull request by ashraidiam**
## Description

Please include a summary of the fix/feature/change, including any relevant motivation and context.

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

### CODE REVIEW

**Comment by themantissa** [comment]
@ashraidiam thank you for the submission.  Can you double check that you completed the CLA - https://www.mongodb.com/legal/contributor-agreement - I don't see your github id on the list.

**Comment by Zuhairahmed** [comment]
Hi @ashraidiam appreciate you creating this PR. Diving deeper into this, both `data "mongodbatlas_team"` and `data "mongodbatlas_teams"` are correct syntax and pose no issues for terraform. That being said, `data "mongodbatlas_teams" ` (existing name of resource in docs) is more helpful to new and existing users because: 
1.  It more closely aligns with the corresponding responding resource name [mongodbatlas_teams](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/teams) 
2. It more closely aligns with underlying Atlas Admin API endpoint path - [https://cloud.mongodb.com/api/atlas/v1.0/orgs/{ORG-ID}/teams](https://www.mongodb.com/docs/atlas/reference/api/teams/) 

Let me know if you're aligned here, if so feel free to close this PR. If not happy to chat more. Again really appreciate your high attention to detail both here and in recent past PRs.

**Comment by ashraidiam** [comment]
@themantissa all done and signed.

**Comment by ashraidiam** [comment]
@Zuhairahmed i do agree, this is a documentation bug rather than a core issue with the provider. I'm picking these up as my IDE is using the terraform language server and predicts. 

I'm guessing the documents are not autogenerated? I have noticed additional/same issues with other resources in the docs. Just not had chance to PR yet.

**Comment by Zuhairahmed** [comment]
@ashraidiam in this case likely not a document bug as name of underlying resource is "Teams" not "Team." See https://www.mongodb.com/docs/atlas/reference/api/teams/ for more details. 

You are are correct our docs are not auto-generated, but this is something we can work towards in the future. Thanks for sharing feedback (as always).

**Pull request closed without merging**
