### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by themantissa**
## Description

I think it's time to remove me from code-owners and leave just the internal engineering team, APIx. 

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue). Please, add the "bug" label to the PR.
- [ ] New feature (non-breaking change which adds functionality). Please, add the "enhancement" label to the PR.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected). Please, add the "breaking change" label to the PR.
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the [contribution guidelines](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/CONTRIBUTING.md)
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

### CODE REVIEW

**Review by gssbzn — APPROVED** [review]
watch has ended

**Review by colm-quinn — APPROVED** [review]
LGTM!

**Review by Zuhairahmed — APPROVED** [review]
LGTM

**Review by Zuhairahmed — APPROVED** [review]
LGTM

**Review by andreaangiolillo — APPROVED** [review]

**Comment by Zuhairahmed** [comment]
@andreaangiolillo do you want to merge this one in since folks are OOTO?

**Pull request merged**
