### PR TITLE
corrected the title by making the variable name plural

### PR DESCRIPTION
**Pull request by crosbymichael1**
## Description

corrected the title by making the variable name plural
from mongodbatlas_network_peering to mongodbatlas_network_peerings

Link to any related issue(s):

## Type of change:
- [x] Documentation fix/enhancement

- [x] signed mongodb contributing agreement

### CODE REVIEW

**Review by themantissa — APPROVED** [review]
LGTM!  Thank you for taking the time to fix these small, but important, items!

**Comment by themantissa** [comment]
@crosbymichael1 before I can merge I need to verify you've signed our CLA, want to check that you've already done so?  Link can be found here: https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/CONTRIBUTING.md

**Comment by crosbymichael1** [comment]
@themantissa I have signed the CLA, thank you.

**Review by themantissa — APPROVED** [review]
LGTM!  CLA confirmed.

**Pull request merged**
