### PR TITLE
Fix typo in federated_settings_org_configs documentation

### PR DESCRIPTION
**Pull request by florenp**
## Description

Please include a summary of the fix/feature/change, including any relevant motivation and context.

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

### CODE REVIEW

**Comment by themantissa** [comment]
@florenp thank you for the PR fix - could you sign our contributor agreement: https://www.mongodb.com/legal/contributor-agreement?

**Comment by florenp** [comment]
@themantissa Contributor agreement signed.

**Comment by themantissa** [comment]
Thank you @florenp!  Will merge and it will go out with our next release.

**Review by themantissa — APPROVED** [review]
LGTM!

**Pull request merged**
