### PR TITLE
Fix create index error msg

### PR DESCRIPTION
**Pull request by ebouther**
## Description

Fixed create index error message.

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have read the Terraform contribution guidelines
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

### CODE REVIEW

**Review by andreaangiolillo — APPROVED** [review]
LGTM

**Comment by themantissa** [comment]
@ebouther great catch, thank you!  Are you sure you signed the CLA?  I checked the list but do not see your github id.  Also we may have to modify this - we currently merge changes to a release branch before master (https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/CONTRIBUTING.md), just fyi.

**Comment by ebouther** [comment]
@themantissa it should be ok now for the CLA.

**Comment by themantissa** [comment]
Thank you @ebouther for signing.

**Review by themantissa — APPROVED** [review]

**Pull request merged**
