### PR TITLE
Improved encryption at rest example

### PR DESCRIPTION
**Pull request by robbertkauffman**
## Description

Improved the encryption at rest on AWS example:
* Create a KMS key instead of using an existing one
* Restricted the IAM policy to only allow access to the KMS key. Current policy allows access to all AWS resources
* Added a readme with instructions
* Removed 2 other encryption at rest examples as these seem redundant and outdated (two-step process and workaround)

Please ignore the previous PR, I used the wrong branch name.

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [X] Documentation fix/enhancement

## Required Checklist:

- [X] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [X] I have read the [contribution guidelines](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/CONTRIBUTING.md)
- [n/a] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [X] I have added any necessary documentation (if appropriate)
- [X] I have run make fmt and formatted my code

### CODE REVIEW

**Review by andreaangiolillo — APPROVED** [review]
LGTM

**Comment by Zuhairahmed** [comment]
thanks @robbertkauffman can you move this to merge to v1.8.1 staging branch instead of master per our [contribution guidelines](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/CONTRIBUTING.md)?

**Comment by Zuhairahmed** [comment]
also @robbertkauffman there a few github linting and other automated checks that are failing as part of your PR. can you please review and resolve?

**Comment by robbertkauffman** [comment]
@Zuhairahmed : I fixed the formatting (one of the automated checks that failed) and changed the base to release-staging-v1.8.1. Another automated check was golint failing but I didn't make any changes to the provider source code, so not clear on why this would fail (perhaps something in master branch that triggered this?).

**Comment by Zuhairahmed** [comment]
Thanks @robbertkauffman, can you sign the MongoDB CLA as well so we can recognize your contribution? https://www.mongodb.com/legal/contributor-agreement 

@martinstibbe can you review this PR as well?

**Comment by robbertkauffman** [comment]
Didn't think it would be necessary as I'm a MongoDB employee, but I just signed it anyway @Zuhairahmed

**Review by Zuhairahmed — APPROVED** [review]
LGTM. thanks again @robbertkauffman! your README in particular is super useful, along with all other fixes.

**Review by martinstibbe — APPROVED** [review]
LGTM

**Pull request merged**
