### PR TITLE
update README - added plugin dev override

### PR DESCRIPTION
**Pull request by abner-dou**
## Description

Added block in README about how to override provider for dev plugin use

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

### CODE REVIEW

**Review by leofigy — APPROVED** [review]
LGTM

**Comment by abner-dou** [comment]
Hi @themantissa , I'm trying to add a mongo reviewer to this PR using `apiX` or `@apiX` but nothing appears :/
this may be a permissions issue?

**Comment by themantissa** [comment]
@abner-dou just tried and it's actually mongodb/apix  try that and see if it works please.

**Review by themantissa — APPROVED** [review]
Thank you for adding this!   LGTM

**Review by threebee — APPROVED** [review]
LGTM!

**Pull request merged**
