### PR TITLE
Rename team.html.markdown into teams.html.markdown

### PR DESCRIPTION
**Pull request by leo-ferlin-sutton**
## Description

On the [documentation website](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/), both in the URL and in the search menu the it shows up as `team` or `mongodbatlas_team` singular when the resource name is `mongodbatlas_teams`.

This is the only resource where the documentation page is spelled differently so I assumed it was a mistake. Same for the data source.

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [X] Documentation fix/enhancement

## Required Checklist:

- [X] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [X] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

### CODE REVIEW

**Comment by themantissa** [comment]
@leo-ferlin-sutton thank you for the PR.  The file names are indeed incorrect however the PR is incomplete.  If you rename the files the links to them from the documentation index and any where teams might be linked to in the docs, will now break.   If you want to correct this completely we'll need the full docs directory searched for instances of the old name and updated with the new.   If you do not want to add to the PR let us know and we'll close and add it to our backlog.

**Comment by leo-ferlin-sutton** [comment]
You are correct, I overlooked the index and did not think to update it. I have pushed a new commit with the change.

I have searched and found no other place where `team` was linked in the documentation (I only looked at the `website` directory and it's subdirectories).

**Comment by themantissa** [comment]
Thank you @leo-ferlin-sutton!   Appreciate the extra effort here.

**Review by themantissa — APPROVED** [review]
LGTM!

**Review by Zuhairahmed — APPROVED** [review]
Great catch @leo-ferlin-sutton. LGTM

**Pull request merged**
