### PR TITLE
INTMDB-331 - Update GCP documentation

### PR DESCRIPTION
**Pull request by evertsd**
## Description

Updated documentation and examples to inform usage of gcp forwarding rules with the mongodbatlas_privatelink_endpoint_service resource

Addresses issue [753](https://github.com/mongodb/terraform-provider-mongodbatlas/issues/753)

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have read the Terraform contribution guidelines
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

### CODE REVIEW

**Review by Zuhairahmed — APPROVED** [review]
Fix updates both documentation as well as default variable names in .tf files. User signed CLA.

**Comment by themantissa** [comment]
@martinstibbe  since you worked on this in the HELP ticket would you mind doing a quick review?

**Review by themantissa — APPROVED** [review]
LGTM, glad to have these corrected!

**Review by martinstibbe — APPROVED** [review]
LGTM

**Review by colm-quinn — APPROVED** [review]
LGTM

**Pull request merged**
