### PR TITLE
fix-#40: added true value by defualt on provider_encrypt_ebs_volume attr

### LINKED ISSUE #40: AWS clusters default provider_encrypt_ebs_volume to false
Hey folks,

If I omit `provider_encrypt_ebs_volume` in my resource definition for an AWS cluster, this value defaults to `false`. However, the [Atlas API](https://docs.atlas.mongodb.com/reference/api/clusters-create-one/) defaults this to `true`.

I think it would also be beneficial to remove `provider_encrypt_ebs_volume: false` from the Example AWS cluster in the [**mongodbatlas_cluster** docs](https://www.terraform.io/docs/providers/mongodbatlas/r/cluster.html) as encrypting your volume is the preferred config.

Thanks!

### PR DESCRIPTION
**Pull request by PacoDw**
closes #40

### CODE REVIEW

**Review by themantissa — APPROVED** [review]
Thank you!  I'll submit a PR for the example change in a bit!

**Review by marinsalinas — COMMENTED** [review]
LGTM but, why did you choose to fix it like this instead of using `Default: true` in the schema definition like we've done here:

https://github.com/terraform-providers/terraform-provider-mongodbatlas/blob/26f10ee1c268910ae659a80e2760f5c88c4e099d/mongodbatlas/resource_mongodbatlas_cluster.go#L50

**Comment by PacoDw** [comment]
@marinsalinas it didn´t work because the schema doesn´t allow you when you have set the computed attribute

**Review by themantissa — APPROVED** [review]
I'm good so approving but Marin is the final word on this one per his question.  Thanks!

**Review by marinsalinas — APPROVED** [review]
LGTM!

**Pull request merged**
