### PR TITLE
INTMDB-834: Address Follow Up comments in INTMDB-804

### PR DESCRIPTION
**Pull request by andreaangiolillo**
## Description

This PR addresses the following comments:

- https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1174#discussion_r1201390141
> agree and helpful. effectively since sink only has max of type of item, in our docs we can replace sink.0.provider, sink.0.region, etc. with sink_provider, sink_region. current docs format is helpful when we have a TypeLists with multiple types of inputs in which in those cases no change is needed. if you are aligned @andreaangiolillo and @maastha can we adopt this format for all PRs going forward as well as get corrected in PR that has already been merged (see [here](https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1163/files#diff-ebd5e08c7fa8e4f0fee0f3b1c8c687c52fd98ce77434a1053e591ee3952d7902R91))?

- https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1174#issuecomment-1559094732

> I believe we forgot to update the example in https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1159. FYI martinstibbe. I will open a follow-up PR to fix the test for the release branch.

Ticket: [INTMDB-834](https://jira.mongodb.org/browse/INTMDB-834)

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue). Please, add the "bug" label to the PR.
- [ ] New feature (non-breaking change which adds functionality). Please, add the "enhancement" label to the PR.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected). Please, add the "breaking change" label to the PR.
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have read the [contribution guidelines](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/CONTRIBUTING.md)
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

### CODE REVIEW

**Review by themantissa — APPROVED** [review]
Thank you for knocking this out from the comment!  LGTM!

**Review by colm-quinn — APPROVED** [review]
LGTM

**Review by martinstibbe — APPROVED** [review]
LGTM

**Comment by andreaangiolillo** [comment]
@pierwill @jwilliams-mongo @zach-carr I am going to merge this PR as this is fixing a failing test. I will open a followup PR to address your comment if any. Thanks!

**Pull request merged**
