### PR TITLE
Organization Resource and Data Source

### PR DESCRIPTION
**Pull request by PacoDw**
Added:

- mongodbatlas_organization resource.
- mongodbatlas_organization resource acceptance testing.
- mongodbatlas_organization resource website documentation.
- mongodbatlas_organization data source.
- mongodbatlas_organization data source acceptance testing.
- mongodbatlas_organization data source website documentation.

Example Configuration:
```hcl
resource "mongodbatlas_organization" "test" {
	name = "organizationName"
}

data "mongodbatlas_organization" "test" {
	org_id = "${mongodbatlas_organization.test.id}"
}
```

### CODE REVIEW

**Review by themantissa — COMMENTED** [review]
due to issues with create this work is on hold

**Comment by themantissa** [comment]
Since we are replacing this closing this PR.

**Comment by vnynr** [comment]
What are you replacing this with? Looking at provisioning Atlas orgs with TF. Is this on roadmap?

**Comment by themantissa** [comment]
@vnynr Hello - currently creating organizations is not supported via the API: https://docs.atlas.mongodb.com/reference/api/organizations/ hence we cannot support it in Terraform (which uses the Atlas API).  This is because API keys are scoped to an organization level so you don't have an API key until you create an org, hence Org is an item that must exist before starting with Terraform.   If you are looking to scope access to a hierarchical construct tin Atlas I'd suggest looking at projects, which is currently supported.

**Pull request closed without merging**
