### PR TITLE
Add "Sensitive: true" for securing sensitive data in state

### PR DESCRIPTION
**Pull request by KeisukeYamashita**
## Description
Access tokens and API keys are sensitive data that should be stored as sensitive data.
Therefore, I've added `Sensitive: true` for those fields in the `alert_configuration` data source and resource.

Thanks in advance.

See https://www.terraform.io/docs/state/sensitive-data.html for more details.

I can't find any link to sign the MongoDB CLA. Could you please tell me how I can sign it? Thanks.

Link to any related issue(s): 

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the MongoDB CLA
- [x] I have read the Terraform contribution guidelines 
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirments
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

### CODE REVIEW

**Comment by themantissa** [comment]
@KeisukeYamashita thank you for the submission!  We would like to be able to review the PR but we do require that any submitters to the Provider sign the MongoDB CLA and that is not yet checked on the PR.  Would you mind signing that first?   Thank you!!

**Comment by KeisukeYamashita** [comment]
@themantissa Thank you for your quick response.
I couldn't find any link or document to sign the MongoDB CLA. Could you please tell me how I can sign it? Thanks in advance.

**Comment by KeisukeYamashita** [comment]
@themantissa Sorry, I found the [Contributor Agreement](https://www.mongodb.com/legal/contributor-agreement) page and signed. PTAL 🙇 

image

**Review by leofigy — APPROVED** [review]

**Review by coderGo93 — APPROVED** [review]
LGTM

**Comment by themantissa** [comment]
@KeisukeYamashita thank you for waiting.  I've confirmed the CLA has been signed and will now approve and merge this contribution in.  Thank you very much!

**Review by themantissa — APPROVED** [review]
LGTM!

**Pull request merged**
