### PR TITLE
doc: remove 3rd shard from 2 shard global cluster example

### PR DESCRIPTION
**Pull request by BassT**
## Description

Please include a summary of the fix/feature/change, including any relevant motivation and context.

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue). Please, add the "bug" label to the PR.
- [ ] New feature (non-breaking change which adds functionality). Please, add the "enhancement" label to the PR.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected). Please, add the "breaking change" label to the PR.
- [ ] This change requires a documentation update
- [x] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have read the [contribution guidelines](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/CONTRIBUTING.md)
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

### CODE REVIEW

**Review by andreaangiolillo — COMMENTED** [review]
Hi @BassT,
Thank you for your contribution! Could you kindly provide some additional clarification regarding the changes made in your PR? Specifically, in the example provided, the definition outlines a scenario where there's a global cluster spanning across 2 zones, and within each zone, there are 3 shards.

**Comment by BassT** [comment]
Hi @andreaangiolillo,

The comment in [line 61](https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1423/files#diff-f26c7f83281cc1f5189540599f12a4345fc1c7a4f3b588dfc1ff6d627a79eb35L61) suggests that "zone n2" is supposed to be a 2-shard zone but lists 3 shards.

"shard n3" in "zone n2" falls out of line because it's the only shard located in the US while the other two shards of this zone are located in Europe.

For the sake of clarity I suggest removing "shard n3" of "zone n2". Alternatively, the comment on "zone n2" could be changed to "3-shard Multi-Cloud Cluster" and the region of "shard n3" to one in Europe.

**Comment by andreaangiolillo** [comment]
I see, thanks for the clarification!

**Review by andreaangiolillo — APPROVED** [review]
LGTM

**Pull request merged**
