### PR TITLE
Update project_api_key.html.markdown

### PR DESCRIPTION
**Pull request by ThomasVictoria**
Remove spare bracket

## Description

Just remove a useless bracket from the `mongodbatlas_project_api_key` resource

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have read the [contribution guidelines](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/CONTRIBUTING.md)
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

### CODE REVIEW

**Comment by Zuhairahmed** [comment]
@ThomasVictoria this is a great catch. Few comments: 
1. Please make sure to sign our Contributors Agreement: https://www.mongodb.com/legal/contributor-agreement
2. PRs are submitted against the current release branch, not master. The naming of the current release branch is release-staging-v1.8.1
3. Please review all other contributing guidelines: https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/CONTRIBUTING.md

**Review by martinstibbe — CHANGES_REQUESTED** [review]
Can we direct this at release-staging-v1.8.1 branch vs master

**Comment by ThomasVictoria** [comment]
> @ThomasVictoria this is a great catch. Few comments: 
> 1. Please make sure to sign our Contributors Agreement: https://www.mongodb.com/legal/contributor-agreement
> 2. PRs are submitted against the current release branch, not master. The naming of the current release branch is release-staging-v1.8.1
> 3. Please review all other contributing guidelines: https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/CONTRIBUTING.md

Just signed the contributor agreement

**Review by Zuhairahmed — APPROVED** [review]
LGTM, thanks again @ThomasVictoria!

**Pull request merged**
