### PR TITLE
Setting deterministic encoding id output, just sorting the keys

### PR DESCRIPTION
**Pull request by leofigy**
## Description

behaviour found by Edgar, sometimes the encodeStateID function generates a different ID with the same input.
This is given it encodes iterating over a map, and maps are unordered, the iteration sequence is not ensure.

So quick fix, sort the keys and access in that way to encode the ID. 

Link to any related issue(s): 

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the MongoDB CLA
- [x] I have read the Terraform contribution guidelines 
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirments
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

### CODE REVIEW

**Comment by coderGo93** [comment]
Hi, I tried myself with cmd `make testacc` it seem It didn't fail with state error related, could you delete the func `SkipTestImport` so it can try in github actions and see if it really works, @leofigy ?

**Comment by leofigy** [comment]
Sure, let me do the update :)

**Comment by gssbzn** [comment]
Please don't forget to sign our CLA https://www.mongodb.com/legal/contributor-agreement

**Comment by leofigy** [comment]
Hi @coderGo93 removed the skipImportTest function, and it worked, previous execution failed with the capacity error, but that's independent

**Comment by coderGo93** [comment]
@leofigy Thank you so much, indeed there are not errors about import state id or related, if there are similar error about capacity, probably need to change the region to `US_EAST_1` or the config using a project created, but not sure if that changes should be made in this PR or another PR @themantissa .

**Comment by themantissa** [comment]
@coderGo93 let's do that work, fix any tests not using larger regions and ensure existing project/new project is use to avoid conflicts, in another PR.   We can create a Jira ticket for it and then schedule some time.

**Review by themantissa — APPROVED** [review]
LGTM!  Please have Abraham create a ticket for the work noted but not yet covered to fix tests.

**Review by coderGo93 — APPROVED** [review]
LGTM

**Pull request merged**
