### PR TITLE
INTMDB-264: Release v1.1.0

### PR DESCRIPTION
**Pull request by abner-dou**
## Description

Release v1.1.0

Link to any related issue(s):[INTMDB-264](https://jira.mongodb.org/browse/INTMDB-264)

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

### CODE REVIEW

**Review by themantissa — COMMENTED** [review]
LGTM!

**Comment by themantissa** [comment]
Added APIx as would like a review but Dublin is likely offline, so added two people to increase chance of PR today.

**Review by thetonymaster — APPROVED** [review]
LGTM

**Review by themantissa — APPROVED** [review]

**Review by threebee — APPROVED** [review]
LGTM

**Pull request merged**
