### PR TITLE
fix: code cleanup

### PR DESCRIPTION
**Pull request by AlphaWong**
code cleanup.

if conditions `provider_instance_size_name ` too many

### CODE REVIEW

**Comment by leofigy** [comment]
Thanks for the clean-up it improves the readability, once one of member of our team approves, and verify the CLA agreement, we can accept it.

**Comment by themantissa** [comment]
@AlphaWong just to check since the PR template was not used, did you sign our CLA?  https://www.mongodb.com/legal/contributor-agreement

**Comment by AlphaWong** [comment]
> @AlphaWong just to check since the PR template was not used, did you sign our CLA? https://www.mongodb.com/legal/contributor-agreement

just signed

**Comment by themantissa** [comment]
@AlphaWong I'll get internal confirmation then, thank you1

**Comment by themantissa** [comment]
CLA signed - BIZSYS-20999

**Review by themantissa — APPROVED** [review]
LGTM!  Thank you - @coderGo93 or @leofigy can one of you approved for a double check.

**Review by leofigy — APPROVED** [review]
LGTM

**Pull request merged**
