### PR TITLE
Fix: small doc error

### PR DESCRIPTION
**Pull request by lescactus**
Remove duplicate word in network_peering documentation

## Description

Please include a summary of the fix/feature/change, including any relevant motivation and context.

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

### CODE REVIEW

**Comment by themantissa** [comment]
@lescactus thank you for the submission.  As soon as we get a chance we'll verify the CLA and review.

**Comment by themantissa** [comment]
@lescactus I'd like to approve and merge this but I cannot find your name on the CLA signer list.  Did you sign https://www.mongodb.com/legal/contributor-agreement?  If so was it using your displayed github name?

**Comment by lescactus** [comment]
@themantissa Can you check again ? I signed with this github username 
Thanks

**Comment by themantissa** [comment]
Absolutely @lescactus - let me look into what's going on.

**Comment by themantissa** [comment]
@lescactus we finally got sorted!  Will approve and merge now.   Docs changes go out with releases so you'll see it in the next release. Thanks!

**Review by themantissa — APPROVED** [review]
LGTM

**Pull request merged**
