### PR TITLE
INTMDB-343: Update go from 1.16 to 1.17 add windows arm64 build support

### PR DESCRIPTION
**Pull request by martinstibbe**
## Description

INTMDB-343: Update go from 1.16 to 1.17 add windows arm64 build support

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

### CODE REVIEW

**Review by Zuhairahmed — APPROVED** [review]
approved pending pass on acceptance tests

**Comment by themantissa** [comment]
@martinstibbe all the tests are failing.  Please rerun and don't request a review till tests are green. Thanks.

**Review by gssbzn — APPROVED** [review]
LGTM

**Review by themantissa — APPROVED** [review]
LGTM, all approved, let's merge

**Pull request merged**
