### PR TITLE
Update cloud_provider_snapshots.html.markdown

### PR DESCRIPTION
**Pull request by nhuray**
## Description

Minor typo on the name of the resource

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

### CODE REVIEW

**Comment by themantissa** [comment]
Thank you @nhuray for the PR but this is actually correct.  There is both a mongodbatlas_cloud_provider_snapshot and mongodbatlas_cloud_provider_snapshots, this is the data source doc for mongodbatlas_cloud_provider_snapshots.  Hence closing this PR out.

**Comment by nhuray** [comment]
@themantissa 

There's **datasources** `mongodbatlas_cloud_provider_snapshot` and `mongodbatlas_cloud_provider_snapshots` but if I'm not mistaken there's only 1 **resource** `mongodbatlas_cloud_provider_snapshot`  (without `s`). 

Just to let you know I also spotted some discrepancies in the documentation using `group_id` instead of `project_id`.  I guess the code has been updated recently but the documentation is still behind.

Regards,

**Comment by themantissa** [comment]
@nhuray I obviously missed that.  You are correct.   If you can sign our [CLA](https://www.mongodb.com/legal/contributor-agreement) I can approve and merge this.  

Originally projects were called groups.  Due to that there's still places in the Atlas docs, this work included, that still contain groups instead of projects.   As we find them we correct them but if you see one feel free to submit a PR.

**Comment by nhuray** [comment]
@themantissa I just signed the CLA. 

I'll try during the week to submit another PR with the discrepancies I found. 

Regards,

**Comment by themantissa** [comment]
@nhuray thank you!  Appreciate the contribution.

**Review by themantissa — APPROVED** [review]

**Pull request merged**
