### PR TITLE
docs(website): fix `federated_settings_org_config` resource name by removing the misleading trailing `s`

### PR DESCRIPTION
**Pull request by Horgix**
## Description

Due to the file name, the resource `federated_settings_org_config` is actually caled `federated_settings_org_configs` in the Terraform Registry documentation (notice the superfluous trailing `s`).

2022-11-09-135813_1052x512_scrot

This simply renames the file to fix this.

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [X] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [X] I have added any necessary documentation (if appropriate)
- [X] I have run make fmt and formatted my code

I didn't find any clean way to "test" the website part so I left that unchecked. I'd be happy to read any instructions on how to validate such a documentation change!

## Further comments

None.

### CODE REVIEW

**Comment by Horgix** [comment]
CLA signed :heavy_check_mark: :slightly_smiling_face: Approved on my company's side by @francoisfanuel

**Review by Zuhairahmed — APPROVED** [review]
Thanks @Horgix! Also confirming that you signed our CLA, this is a good catch. LGTM

**Review by andreaangiolillo — APPROVED** [review]
LGTM

**Comment by Horgix** [comment]
Thanks for the reviews! :relaxed: 

What's the next step to get this merged? Do I need to do anything else on my end? :slightly_smiling_face:

**Review by themantissa — APPROVED** [review]
LGTM!

**Comment by Zuhairahmed** [comment]
Just merged @Horgix , thanks again for your contribution!

**Pull request merged**
