### PR TITLE
INTMDB-357: Add exclude to skip go-header until google terraform provider version tag upgrade

### PR DESCRIPTION
**Pull request by martinstibbe**
## Description

INTMDB-357: Add exclude to skip go-header until google terraform provider version tag upgrade

Link to any related issue(s):

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

### CODE REVIEW

**Review by themantissa — APPROVED** [review]
LGTM, added APIx for double check.

**Review by gssbzn — APPROVED** [review]
LGTM with a question, shouldn't this include a change to go.sum? the issue came by looking at the go.sum if this doesn't change the go.sum I'm not sure it's worth the change

**Comment by martinstibbe** [comment]
@gssbzn Added another commmit to pickup mod.sum update

**Review by gssbzn — APPROVED** [review]
LGTM thanks for including the sum file

**Pull request merged**
