### PR TITLE
refactor: Migrates advanced_cluster resource to TPF - DO NOT DELETE BRANCH

### PR DESCRIPTION
**Pull request by maastha**
## Description

Please include a summary of the fix/feature/change, including any relevant motivation and context.

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue). Please, add the "bug" label to the PR.
- [ ] New feature (non-breaking change which adds functionality). Please, add the "enhancement" label to the PR.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected). Please, add the "breaking change" label to the PR.
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the [contribution guidelines](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/CONTRIBUTING.md)
- [ ] I have checked that this change does not generate any credentials and that **they are NOT accidentally logged anywhere**.
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code
- [ ] If changes include deprecations or removals, I defined an isolated PR with a relevant title as it will be used in the auto-generated changelog.

### CODE REVIEW

**Comment by AgustinBettati** [comment]
@maastha Do you believe the branches related to the cluster TPF migration could be of value when we revisit this migration? Just want to make sure we don't lose these branches if that is the case.

**Comment by maastha** [comment]
@AgustinBettati yes these branches are useful and should NOT be deleted. I have made these branches protected for now. Let me know if anything else should be done

**Comment by maastha** [comment]
DO NOT DELETE BRANCH!!!

**Comment by andreaangiolillo** [comment]
Should we rename the branch name to include `do_not_delete` and document somewhere the reason why they should not be deleted? @maastha

**Pull request closed without merging**
