### PR TITLE
Address test failures with v1.4.5

### PR DESCRIPTION
**Pull request by evertsd**
## Description

Get a passing pipeline for v1.4.5 by addressing failures with [this pipeline](https://github.com/mongodb/terraform-provider-mongodbatlas/runs/8077984947?check_suite_focus=true)
- Skip some test failures which will be addressed in v1.4.6
- Fix a couple bad test configs which were improperly passing prior to v1.4.5

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have read the Terraform contribution guidelines
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

### CODE REVIEW

**Comment by evertsd** [comment]
There's one last test failure in the pipeline mentioned on the description, that being https://github.com/mongodb/terraform-provider-mongodbatlas/runs/8077984947?check_suite_focus=true#step:4:845

The test is complaining about no valid credential sources for AWS provider, however when checking the test here the credentials seem to be set up appropriately https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/mongodbatlas/resource_mongodbatlas_cloud_backup_schedule_test.go#L120

**Comment by evertsd** [comment]
@martinstibbe answered the above question, will address in `v1.4.6`, thanks.

**Review by themantissa — APPROVED** [review]
LGTM.  Note we'll be addressing the alert failures in 1.4.6. but skipping to unblock release of current issues.

**Review by martinstibbe — APPROVED** [review]
LGTM

**Pull request merged**
