### PR TITLE
fix: small error

### PR DESCRIPTION
**Pull request by 0xflotus**
## Description

I fixed a small typo error in the Environmental Varaibles

Link to any related issue(s):

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code

### CODE REVIEW

**Comment by themantissa** [comment]
@0xflotus thank you! Will verify the CLA has been signed.

**Review by themantissa — APPROVED** [review]
LGTM!  @coderGo93 @leofigy can you confirm this is correct and is a typo only?

**Comment by themantissa** [comment]
Note: CLA confirmed

**Comment by leofigy** [comment]
Hi @themantissa is not just a typo, It's everywhere :0 

`leofigy@msi-desktop:~/mongo/terraform-provider-mongodbatlas$ grep -R "AZURE_SUBCRIPTION_ID" . 
./website/docs/r/network_peering.html.markdown:  azure_subscription_id = local.AZURE_SUBCRIPTION_ID
./mongodbatlas/resource_mongodbatlas_network_peering_test.go:		subcrptionID      = os.Getenv("AZURE_SUBCRIPTION_ID")
./mongodbatlas/provider_test.go:		os.Getenv("AZURE_SUBCRIPTION_ID") == "" ||
./mongodbatlas/provider_test.go:		t.Fatal("`AZURE_DIRECTORY_ID`, `AZURE_SUBCRIPTION_ID`, `AZURE_VNET_NAME` and `AZURE_RESOURCE_GROUP_NAME` must be set for  network peering acceptance testing")
./mongodbatlas/provider_test.go:		os.Getenv("AZURE_SUBCRIPTION_ID") == "" ||
./mongodbatlas/provider_test.go:		t.Fatal(`'AZURE_CLIENT_ID','AZURE_CLIENT_ID_UPDATED', 'AZURE_SUBCRIPTION_ID',
./mongodbatlas/resource_mongodbatlas_encryption_at_rest_test.go:			SubscriptionID:    os.Getenv("AZURE_SUBCRIPTION_ID"),
./mongodbatlas/resource_mongodbatlas_encryption_at_rest_test.go:			SubscriptionID:    os.Getenv("AZURE_SUBCRIPTION_ID"),
./mongodbatlas/resource_mongodbatlas_cluster_test.go:		subcrptionID      = os.Getenv("AZURE_SUBCRIPTION_ID")
./mongodbatlas/resource_mongodbatlas_cluster_test.go:		subcrptionID      = os.Getenv("AZURE_SUBCRIPTION_ID")
./.github/workflows/automated-test-acceptances.yml:          AZURE_SUBCRIPTION_ID: ${{ secrets.AZURE_SUBCRIPTION_ID }}
./README.md:$ export AZURE_SUBCRIPTION_ID=<YOUR_SUBCRIPTION_ID>
./README.md:export AZURE_SUBCRIPTION_ID=<YOUR_SUBCRIPTION_ID>
`
Thanks @0xflotus for the catch

**Comment by themantissa** [comment]
@leofigy I worried that might be the case.  @0xflotus we will have to decline on this PR as we need to fix the actual spelling in the code and then the docs.  We'll create an internal ticket to do so unless you'd like to take that on.   Thank you.

**Pull request closed without merging**
