### PR TITLE
Replaced the digest auth library with one that supports SHA-256

### PR DESCRIPTION
**Pull request by MihaiBojin**
## Description

- replaced https://github.com/Sectorbob/mlab-ns2 with https://github.com/mongodb-forks/digest (which supports both MD5 and SHA-256 digest access auth headers / [RFC7616](https://tools.ietf.org/html/rfc7616))
- cleaned the module dependencies (`go mod tidy`)
- updated the vendored dependencies with `go mod vendor`
- the current test suite should catch any issues (we have made the same change in [mongocli](https://github.com/mongodb/mongocli) and tested it in all configurations)

Link to any related issue(s): 

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the MongoDB CLA
- [x] I have read the Terraform contribution guidelines 
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirments
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

### CODE REVIEW

**Review by gssbzn — APPROVED** [review]
LGTM

**Comment by MihaiBojin** [comment]
I ran the cleanup operations in #272 to make this PR easier to review.

**Review by PacoDw — APPROVED** [review]
Nice! LGTM 👍

**Review by themantissa — APPROVED** [review]
LGTM, thank you for knocking this out.

**Review by gssbzn — APPROVED** [review]
restamp

**Pull request merged**
