### PR TITLE
Fix timeout in acctest

### PR DESCRIPTION
**Pull request by abner-dou**
## Description

A fix was apply to change the timeout on acctest (now is necessary a env var called `ACCTEST_TIMEOUT`), also a minor changes to serverless debug messages was made

Link to any related issue(s):

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

### CODE REVIEW

**Review by coderGo93 — APPROVED** [review]
LGTM

**Review by themantissa — APPROVED** [review]
Approving with the understanding that there will still be at least state timeouts per slack discussion. 

Thank you for the text edits as well - this shows we all really need to keep an eye out better for misses like this.

**Comment by themantissa** [comment]
@threebee and @gssbzn sorry to add you both but we are way behind on tests and hoping this will help remove failures we are seeing.  Would like one of you to give it a look before proceeding, if possible.

**Review by gssbzn — APPROVED** [review]
LGTM

**Review by themantissa — APPROVED** [review]

**Review by coderGo93 — APPROVED** [review]
LGTM

**Pull request merged**
