### PR TITLE
Terraform resource for MongoDB Custom Roles

### PR DESCRIPTION
**Pull request by mpaluchowski**
**Work in progress**. Opening a draft pull request to show progress on this and perhaps occasionally ask for advice.

Adding a new resource for managing Custom MongoDB Roles. This follows my earlier pull request mongodb/go-client-mongodb-atlas#20 adding the necessary functionality to the Go client.

### Resource
- [x] Schema
- [x] Creation
- [x] Reading
- [x] Updating
- [x] Deletion
- [x] Import
- [x] Testing file
- [ ] Documentation
### Data source
- [x] Schema
- [x] Reading
- [ ] Testing file
- [ ] Documentation

### CODE REVIEW

**Comment by themantissa** [comment]
@mpaluchowski looks like you are coming along nicely on this, thank you.  Do you feel a review would help?

**Comment by PacoDw** [comment]
Hello @mpaluchowski, I edited the task list adding complementary tasks to create the resource, I will help with the testing file for the resource because I need to validate the resource tasks to be able to continue, everything seems pretty well.

Thank you so much!

**Comment by mpaluchowski** [comment]
Thanks for the poke. I haven't had time to work on the code since December, until now. I think the logic should be roughly complete at this point -- barring more linting errors. Of course, it still needs a test file, which I'll try to work on over the next few days.

**Comment by PacoDw** [comment]
@mpaluchowski Thank you so much! I almost have the Test file so don't worry about it, I think today or tomorrow I do the commit it along with some other little changes.

**Comment by themantissa** [comment]
Thank you @mpaluchowski!  Just pinged as we have some time to help on this now and it would be great to get it in the next version of the provider, hence @PacoDw providing some extra assistance.

**Comment by mpaluchowski** [comment]
Alright. Should I also submit documentation or do you prefer to write it?

**Comment by PacoDw** [comment]
First, I will create the data source test file to validate it and leave the documentation at the end.

**Comment by PacoDw** [comment]
@mpaluchowski  could you open again plz? I made a mistake and closed it 😢

**Comment by mpaluchowski** [comment]
:rofl: I don't see a "reopen" button anywhere, so I guess I'll have to submit a new pull request. Let me check.

**Comment by PacoDw** [comment]
I'm so sorry for that :S

**Comment by mpaluchowski** [comment]
Uhm. Looks like it's all mixed up now. The branch in my fork has only the last two commits now: 3f5f527 and 00cb7e1, but the brand in the original repository at terraform-providers has all the other commits, up to f45a00f.

I'd need to dig into the reflog to get back my commits in my fork. But since the branch is copied to your repository, you should be able to open an internal pull request here.

**Comment by PacoDw** [comment]
Okay let me check that, thank you so much!

**Pull request closed without merging**
