### PR TITLE
doc: Update README.md with supported OS/Arch

### PR DESCRIPTION
**Pull request by andreaangiolillo**
## Description

This PR updates the readme.md to add the supported os/arch

Link to any related issue(s):[ INTMDB-959]( https://jira.mongodb.org/browse/INTMDB-959)

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue). Please, add the "bug" label to the PR.
- [x] New feature (non-breaking change which adds functionality). Please, add the "enhancement" label to the PR.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected). Please, add the "breaking change" label to the PR.
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have read the [contribution guidelines](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/CONTRIBUTING.md)
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

### CODE REVIEW

**Review by colm-quinn — APPROVED** [review]
LGTM, thanks for adding!

**Review by gssbzn — COMMENTED** [review]
Can we also document this on the public/registry page?

**Comment by andreaangiolillo** [comment]
> Can we also document this on the public/registry page?

Leave this question to @Zuhairahmed

**Comment by Zuhairahmed** [comment]
> > Can we also document this on the public/registry page?
> 
> Leave this question to @Zuhairahmed

No concerns, would add this same detail here: https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs

**Pull request merged**
